name: Set Up and Verify Python Environment

on:
  push:
    branches:
      - "*"

jobs:
  setup-python-environment:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    # Upgrade pip and install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
    
    # Verify Python version
    - name: Check Python version
      run: python --version
    
    # Verify flake8 installation
    - name: Run Flake8 Linting
      run: flake8 --version
    
    # Verify pytest installation
    - name: Run Pytest
      run: pytest --version

